services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:984
    volumes:
      - /home/joanorrit/jellyfin:/config
      - /home/joanorrit/jellyfin/movies:/movies:ro
      - /home/joanorrit/jellyfin/tv-shows:/tv-shows:ro
    networks:
      - proxy-network
    ports:
      - 8096:8096
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
    - PUID=1000
    - PGID=984
    - TZ=Etc/UTC
    - AUTO_UPDATE=true
    volumes:
      - /home/joanorrit/jellyfin/jackett/config:/config
      - /home/joanorrit/jellyfin/jackett/downloads:/downloads
    networks:
      - proxy-network
    ports:
      - 9117:9117
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Etc/UTC
    volumes:
      - /home/joanorrit/jellyfin/transmission/config:/config
      - /home/joanorrit/jellyfin/transmission/downloads:/downloads
      - /home/joanorrit/jellyfin/transmission/watch:/watch
    networks:
      - proxy-network
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/joanorrit/jellyfin/qbittorrent/config:/config
      - /home/joanorrit/jellyfin/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Etc/UTC
    volumes:
      - /home/joanorrit/jellyfin/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/joanorrit/jellyfin/nginx/data/:/data/
    networks:
      - proxy-network
    ports:
      - 80:80
    restart: unless-stopped

networks:
  proxy-network:
    name: proxy-network
    driver: bridge
