services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:984
    volumes:
      - ${JELLYFIN_CONFIG}:/config
      - ${JELLYFIN_MOVIES}:/movies:ro
      - ${JELLYFIN_TV_SHOWS}:/tv-shows:ro
    networks:
      - proxy-network
    ports:
      - 8096:8096
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
    - PUID=1000
    - PGID=984
    - TZ=Etc/UTC
    - AUTO_UPDATE=true
    volumes:
      - ${JACKETT_CONFIG}:/config
      - ${JACKET_DOWNLOADS}:/downloads
    networks:
      - proxy-network
    ports:
      - 9117:9117
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Etc/UTC
    volumes:
      - ${TRANSMISSION_CONFIG}:/config
      - ${TRANSMISSION_DOWNLOADS}:/downloads
      - ${TRANSMISSION_WATCH}:/watch
    networks:
      - proxy-network
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Etc/UTC
    volumes:
      - ${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-network
    ports:
      - 80:80
    restart: unless-stopped

networks:
  proxy-network:
    name: proxy-network
    driver: bridge
